### ISSUE TITLE
Developer mode runs in a small portion of the screen

### ISSUE THREAD

**Issue by jrmuizel** [WebKit/MotionMark#44] opened 2024-02-07 19:13 UTC
Compare:
https://browserbench.org/MotionMark1.3/developer.html?warmup-length=2000&warmup-frame-count=30&first-frame-minimum-length=0&test-interval=60&display=progress-bar&tiles=big&controller=ramp&system-frame-rate=60&frame-rate=50&time-measurement=performance&suite-name=MotionMark&test-name=Paths&complexity=5093
vs the 1.2 version
https://browserbench.org/MotionMark1.2/developer.html?warmup-length=2000&warmup-frame-count=30&first-frame-minimum-length=0&test-interval=60&display=progress-bar&tiles=big&controller=ramp&system-frame-rate=60&frame-rate=50&time-measurement=performance&suite-name=MotionMark&test-name=Paths&complexity=5093

**Comment by vmiura** [comment] 2024-02-07 22:06
This looks like a duplicate of #43.

I have a small patch to fix this here https://github.com/vmiura/MotionMarkSnapshot1.3/commit/c07c17693cba5748dab548ff936208d48461fafb

**Comment by smfr** [comment] 2024-02-08 05:22
Victor, could you submit a PR for that?

**Closed** 2024-02-08 05:23 UTC
